---
- name: Install the latest version of git, python3, python3-dev, python3-pip ans setup backendserver
  hosts: backEnd
  become: true
  connection: ssh
  tasks:
  - name: Install git
    yum:
          name: git
          state: latest
  - name: Install python3
    yum:
          name: python3
          state: latest
  - name: Install python3-dev
    yum:
          name: python3-dev
          state: latest
  - name: Install python3-pip
    yum:
          name: python3-pip
          state: latest
  - name: Install virtual environment
    command: pip3 install virtualenv

  - name: Download Chat-app from git
    git:
            repo: "https://github.com/afrozbasha/new_chatapp.git"
            dest: /home/ansibleuser/new_chatapp
            version: master

  - name: create virtual environment env
    command:
            cmd: virtualenv /home/ansibleuser/new_chatapp/env -p python3
            creates: "/home/ansibleuser/new_chatapp/env"
  - name: Install requirements
    pip:

            requirements: /home/ubuntu/requirements.txt
            virtualenv: /home/ansibleuser/new_chatapp/env
            state: present

  - name: copy gunicorn.service file form ansibleuser to backEnd node
    copy:
            src: /home/ubuntu/gunicorn.service
            dest: /etc/systemd/system/
  - name: start gunicorn
    become: true
    command: systemctl daemon-reload

  - name: enable gunicorn
    become: true
    command: systemctl enable gunicorn

  - name: start gunicorn
    become: true
    command: systemctl start gunicorn

